#!/usr/bin/env python
import os
import sys

pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))  # noqa
sys.path.insert(0, pkg_root)  # noqa

import ssds.cli.staging
import ssds.cli.deployment
from ssds.cli import dispatch


if __name__ == "__main__":
    dispatch(sys.argv[1:])
